### ISSUE TITLE
Please release current version

### ISSUE THREAD

**Issue by vmx** [filecoin-project/rust-fil-ffi-toolkit#3]
In order to get

 - https://github.com/filecoin-project/rust-fil-proofs-ffi/pull/25
 - https://github.com/filecoin-project/rust-fil-sector-builder/pull/63

green, I need to get current HEAD released. Thanks.

**Comment by vmx** [comment]
Please don't release yet, there's another PR coming in soon.

**Comment by vmx** [comment]
Please do a release once https://github.com/filecoin-project/rust-fil-ffi-toolkit/pull/4 is merged.

**Comment by laser** [comment]
@vmx - done
